- title: Advanced Engineering Informatics
  category: Journal
  importance: 1

- title: Concurrency and Computation: Practice and Experience
  category: Journal
  importance: 2

- title: Journal of Infrastructure, Policy and Development
  category: Journal
  importance: 3

- title: The 7th Asian Conference on Artificial Intelligence Technology, ACAIT 2023
  category: Conference
  importance: 1